### ISSUE TITLE
Raise error when using asset_path for a js or css file.

### ISSUE THREAD

**Issue by filipegiusti** [ndbroadbent/assets_precompile_enforcer#3]
The non precompiled error can happen when you have a call to asset_path that not present. Do you think it's a good fit for this gem to prevent that too?

**Comment by ndbroadbent** [comment]
Not sure what you mean, please leave a comment and reopen if you are still interested, and could explain a little further.

**Comment by filipegiusti** [comment]
The idea was to have the same behavior on the helper `asset_path` that's added to `javascript_include_tag`.
