### ISSUE TITLE
Raises unnecessary error when using jasminerice

### ISSUE THREAD

**Issue by filipegiusti** [ndbroadbent/assets_precompile_enforcer#4]
With both gems installed when you try to run the tests of jasminerice in /jasmine it fails because jasmine.css isn't precompiled.

The best way to avoid this seems to write an ignore list. Can I start to work on it?

**Comment by ndbroadbent** [comment]
Hi there, sure, that sounds like a good idea!

**Comment by ndbroadbent** [comment]
Hey, this gem now has an ignored list for assets, which can be configured at `Rails.application.config.assets.ignore_for_precompile`. HTH!

**Comment by filipegiusti** [comment]
Absolutely, thanks.
